### ISSUE TITLE
Problem with Typescript ESlinting 

### ISSUE THREAD

**Issue by ramancloudsmartz** [map-gl-indoor/map-gl-indoor#10]
Need to add support for interfaces/types

On the fly created properties causing errors. Properties throwing error for ESLint with strict rules

![image](https://user-images.githubusercontent.com/77831693/143539813-a22692f3-0011-4fc7-bd37-231d31017c14.png)

![image](https://user-images.githubusercontent.com/77831693/143539678-e124c927-e72d-49be-9c8d-e3527a07c92c.png)

![image](https://user-images.githubusercontent.com/77831693/143539563-cb52bd5a-40a3-498b-ad71-969bc51d42e6.png)

**Comment by ramancloudsmartz** [comment]
Simple Workaround is

```
interface MapIndoor {
  addMap?: (map: mapboxgl.Map) => void;
  control?: IControl;
}
```
```
interface MbMapIndoor extends mapboxgl.Map {
  indoor?: MapIndoor;
}
```

**Comment by ThibaudM** [comment]
I was just rewriting this part the last few days. In fact, I have moved the project from rollup to vitejs.
I am not a JS/TS developer so I tried to do my best to provide a good feeling with this library.
The new version is 0.3.0 (https://www.npmjs.com/package/map-gl-indoor) and should solve your problem.

Recommendations and suggestions on the project structure or naming are welcome ;)
