### ISSUE TITLE
How does the plugin work with maplibre-gl-js?

### ISSUE THREAD

**Issue by ricardoalexandre-dev** [map-gl-indoor/map-gl-indoor#11]
First of all, I would like to thank you for your work, this plugin is very interesting, for the ability to integrate indoor maps on top of the mapbox service, because the official version: Mapbox Indoor v1, still beta, the tileset includes data only for Japan and is only available by contacting the sales department of Mapbox in Japan, info [here](https://docs.mapbox.com/data/tilesets/reference/mapbox-indoor-v1/).

You refer: ''The project should works with maplibre-gl-js too''. I would like to know how your plugin works using maplibre-gl-js. On my side I'm doing developments using pure JS, based on the ''tmp-gh-pages'' example. I've also tried making changes to the examples you provide in the ''example'' folder using Typescript. Changing the map style to a Maptiler style, is simple and easy. My problem is not using the 'mapbox-gl' library anymore and just using the 'maplibre-gl-js' library, I noticed that there are some differences between the both libraries. Could you provide an example of how your plugin would work on top of the 'maplibre-gl-js' library or explain what are the main changes to make for that work? 

Thanks again, I look forward to feedback when possible!

**Comment by ThibaudM** [comment]
I have created an example with maplibre v2.0.1 in another branch [https://github.com/map-gl-indoor/map-gl-indoor/blob/feat/maplibre/example/maplibre.ts](https://github.com/map-gl-indoor/map-gl-indoor/blob/feat/maplibre/example/maplibre.ts).
Main functionalities seem to work, but there are some issues related to images and fonts of the [Default Style](https://github.com/map-gl-indoor/map-gl-indoor/blob/main/src/style/DefaultLayers.ts). The default style was built for mapbox streets v10. But, it is up to you to use your own style (see https://github.com/map-gl-indoor/map-gl-indoor/blob/main/example/custom-style.ts).

Let me know if you need more info.

PS: It seems that maplibre has some TS checking issues but we can easily workaround it with an "any" type.

**Comment by ThibaudM** [comment]
I have tried with maptiler streets style but get this error: https://github.com/maplibre/maplibre-gl-js/pull/775
Maybe I should give it another try later.

**Comment by ricardoalexandre-dev** [comment]
Appreciated your quick response, with an example to test, a big thanks. I had success replicating your example and got the same errors with images and fonts using maptiler's basic and streets styles.

I'm considering migrating my project in the future to Typescript, but at the moment I have my developments done in pure JS. From what I understand, your plugin was only compatible for use with 'maplibre-gl-js' after refactoring to Typescript, this means that it will hardly be possible to use your plugin on top of 'maplibre-gl-js' using the oldest examples of pure JS, right? Or do you think that could work also with pure JS using only 'maplibre-gl-js' (v2.0.1 or other versions)?

**Comment by ThibaudM** [comment]
You are right, the project could not be used for maplibre as it is without dependencies on mapbox. 

**Reason:**
In fact, for a sake of commodity, I reused mapbox tools likes LngLatBounds and LngLat directly inside the project. So, for the `umd` export I added the use of `mapboxgl` global variable to access mapbox methods. Maplibre has similar methods but under `maplibregl` global variable. That is why it could not work.

**Changelog / Work in progress:**
To avoid maintenance for both projects (mapbox/maplibre), I refactored the code to use TurfJS. 
I have tested it on the new branch and it works. Just Typescript Definition file could not be generated for the moment (see https://github.com/maplibre/maplibre-gl-js/issues/790#issuecomment-1017351028). When the maplibre type issues will be solved, I will publish a new release.

**Usage:**
In the meanwhile, you can checkout the `feat/maplibre` branch (`main` branch should work too), build the bundle via `npm run build`, and reuse the example mentioned above.

In general, Typescript is not necessary to use `map-gl-indoor`, you can convert the code to Vanilla JS.

**Comment by ThibaudM** [comment]
The problem still exists in maplibre-gl-js v2.1.1

**Comment by ricardoalexandre-dev** [comment]
Big thanks for the update, I'm still pondering how to proceed from here on the possibility of migrating the base maps from mapbox to maplibre, using the plugin. I will come back if any more questions or concerns arise.
