### ISSUE TITLE
This localhost page can’t be found

### ISSUE THREAD

**Issue by rome05** [map-gl-indoor/map-gl-indoor#14]
hellosir. when I run npm run dev and open localhost:3000/examples I am getting "This localhost page can’t be found".. the dev server is running but it doesn't load anything am i missing something?

**Comment by ThibaudM** [comment]
Do you use the http protocol? (without s)

**Comment by rome05** [comment]
yes i did sir but keeps getting the same error

**Comment by ThibaudM** [comment]
My bad. You have to add the last back slash: `http://localhost:3000/example/`. This is missing in the readme

**Comment by rome05** [comment]
ohhh thank you very much its working now.

**Comment by ThibaudM** [comment]
I finally changed the root of vitejs to the example directory, so it's event easier now. You do not need to add `/example/` anymore
