### ISSUE TITLE
MapServerHandler is not defined Erroe

### ISSUE THREAD

**Issue by MG-LSJ** [map-gl-indoor/map-gl-indoor#17]
I'm getting an error `Uncaught ReferenceError: MapServerHandler is not defined`  
I am following [this](https://github.com/map-gl-indoor/map-gl-indoor/blob/main/example/with-map-server.ts) example using the umd version.

**Comment by ThibaudM** [comment]
Using umd version `MapServerHandler` is in `window.mapgl_indoor` object:
![Screenshot 2022-09-29 at 17 14 53](https://user-images.githubusercontent.com/3089186/193070905-a3acd09d-c304-447c-96d7-629f247b31a7.png)
